#　每天一个Pytorch用法

In [1]:
import torch
from torch import nn

# 数据

# 模型

## nn.Paramters的使用
[PyTorch中的torch.nn.Parameter() 详解](https://blog.csdn.net/weixin_44966641/article/details/118730730)

In [5]:
torch.nn.Parameter(torch.randn(1, 2))

Parameter containing:
tensor([[-0.9437,  1.3329]], requires_grad=True)

## nn.Embedding的使用
[Pytorch中的nn.Embedding()](https://blog.csdn.net/qq_38883844/article/details/104331382)

### 初始化Embedding

In [36]:
# Embedding层的创建
embeddings = nn.Embedding(num_embeddings=10, embedding_dim=3)
x = torch.LongTensor([[1, 2, 5, 4], [2, 3, 4, 9]])
out = embeddings(x)
out

tensor([[[-0.6455,  0.7581,  0.3701],
         [-0.2305, -1.3838,  0.5917],
         [-0.1369, -0.2685, -1.9981],
         [-3.5282, -0.1207,  1.8074]],

        [[-0.2305, -1.3838,  0.5917],
         [-1.2788,  0.7246, -0.5846],
         [-3.5282, -0.1207,  1.8074],
         [ 1.2394,  1.1400,  0.3093]]], grad_fn=<EmbeddingBackward>)

In [37]:
# padding_idx的使用
embeddings = nn.Embedding(num_embeddings=10, embedding_dim=3, padding_idx=1)
embeddings.weight

Parameter containing:
tensor([[ 0.2267,  0.3589,  0.7066],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.3672, -0.5855,  1.2222],
        [ 0.1638,  0.9372, -0.7770],
        [ 0.0570,  0.7663, -1.9659],
        [ 0.4338,  0.1755, -0.3985],
        [-0.4119, -0.1239,  0.8188],
        [ 1.3993,  1.3706, -1.7001],
        [-1.4491, -1.0667,  0.2143],
        [-0.0447,  0.5594,  0.7713]], requires_grad=True)

### 加载预训练向量

#### 方法一(建议)

In [38]:
pre_train_embed = torch.rand((4, 5))
embeds = nn.Embedding.from_pretrained(pre_train_embed)

In [39]:
pre_train_embed

tensor([[0.0236, 0.6508, 0.0331, 0.0976, 0.7699],
        [0.3862, 0.3805, 0.3369, 0.1542, 0.6186],
        [0.6175, 0.8434, 0.6832, 0.2313, 0.9607],
        [0.1572, 0.3083, 0.9905, 0.5265, 0.9703]])

In [40]:
embeds.weight

Parameter containing:
tensor([[0.0236, 0.6508, 0.0331, 0.0976, 0.7699],
        [0.3862, 0.3805, 0.3369, 0.1542, 0.6186],
        [0.6175, 0.8434, 0.6832, 0.2313, 0.9607],
        [0.1572, 0.3083, 0.9905, 0.5265, 0.9703]])

In [41]:
#　默认为冻结，即不更新embedding中的参数
embeds.weight.requires_grad

False

#### 方法二

In [42]:
embeds = nn.Embedding(num_embeddings=4, embedding_dim=5)
embeds.weight

Parameter containing:
tensor([[-0.7435,  2.1544,  0.9816,  1.4552,  1.0855],
        [ 1.4446, -0.6006,  2.1655, -1.5185,  0.2170],
        [-0.9108, -0.4313, -0.5445, -1.6522,  0.7080],
        [-1.6187,  0.1293,  0.8513,  2.2911, -1.2237]], requires_grad=True)

In [43]:
embeds.weight = nn.Parameter(torch.rand(4, 5))

In [44]:
embeds.weight

Parameter containing:
tensor([[0.4243, 0.2984, 0.1440, 0.3879, 0.1798],
        [0.8419, 0.7575, 0.7393, 0.9052, 0.1645],
        [0.1252, 0.2824, 0.4781, 0.1542, 0.6495],
        [0.0816, 0.2640, 0.5618, 0.4743, 0.1947]], requires_grad=True)

In [45]:
# 默认该方法需要进行的参数更新
embeds.weight.requires_grad

True

In [46]:
# 设置不更新
embeds.weight.requires_grad = False

In [47]:
embeds.weight.requires_grad

False

#### 方法三

In [48]:
embeds = nn.Embedding(num_embeddings=4, embedding_dim=5)
embeds.weight

Parameter containing:
tensor([[ 0.2325,  0.1292,  0.3445, -0.4335, -3.3033],
        [ 0.3277,  1.0817,  0.4431,  0.3838,  0.1849],
        [ 0.4300, -0.2442,  0.5124, -0.2554,  0.9184],
        [ 0.8845, -1.3623,  0.1273,  1.0796,  1.8181]], requires_grad=True)

In [49]:
embeds.weight.data = torch.rand(4, 5)

In [50]:
embeds.weight

Parameter containing:
tensor([[0.9770, 0.7766, 0.8749, 0.1747, 0.3754],
        [0.1453, 0.9039, 0.3793, 0.8667, 0.4844],
        [0.4188, 0.0663, 0.4424, 0.3559, 0.3196],
        [0.3518, 0.6406, 0.4359, 0.0081, 0.9686]], requires_grad=True)

In [51]:
embeds.weight.requires_grad = False

In [52]:
embeds.weight.requires_grad

False

## nn.Conv1d

## nn.DataParallel

## nn.LayerNorm与nn.BatchNorm

# 损失

## BCELoss与CrossEntropyLoss对比